version: '2'
services:
    super-to-do-list:
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - redis
          - db
    redis:
        image: redis
        ports:
          - "6379:6379"
    db:
        image: postgres
        volumes:
          - ./tmp/db:/var/lib/postgresql/data
        environment:
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"