version: '2'
services:
    super-to-do-list:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "6379:6379"
